version: "3.7"

services:
    web:
        build: ./app
        command: python main.py
        volumes:
            - ./app/:/usr/src/app/
        ports:
            - 8000:8000
        depends_on:
            - db
    db:
        image: postgres:11.5-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=
            - POSTGRES_PASSWORD=
            - POSTGRES_DB=

volumes:
    postgres_data:
